version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    # docker 安全验证
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
